server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_share_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
